<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Language\Language;
use Drupal\translation_workflow_node_block\TranslationWorkflowForm;
use Drupal\translation_workflow_node_block\TranslationWorkflowView;

/**
 * Implements hook_form_alter().
 */
function translation_workflow_node_block_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(TranslationWorkflowForm::class)
    ->formAlter($form, $form_state, $form_id);
}

function translation_workflow_node_block_entity_view_alter(array &$build, Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(TranslationWorkflowView::class)
    ->viewAlter($build, $entity, $display);
}

/**
 * Implements hook_pathauto_alias_alter().
 */
function translation_workflow_node_block_pathauto_alias_alter(&$alias, array &$context) {
  // Force all aliases to be saved with default language.
  $context['language'] = Language::LANGCODE_DEFAULT;
}
